name: zussgo
description: ZussGo - Connect. Explore. Travel Together.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  go_router: ^14.2.0
  supabase_flutter: ^2.5.0
  flutter_dotenv: ^5.1.0
  app_links: ^6.1.1
  image_picker: ^1.1.2
  cached_network_image: ^3.3.1
  timeago: ^3.6.1
  uuid: ^4.4.0
  intl: ^0.19.0
  flutter_animate: ^4.5.0
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.9
  riverpod_generator: ^2.4.0

flutter:
  uses-material-design: true

  assets:
    - .env

  fonts:
    - family: ClashDisplay
      fonts:
        - asset: assets/fonts/ClashDisplay-Variable.ttf

    - family: Satoshi
      fonts:
        - asset: assets/fonts/Satoshi-Variable.ttf
        - asset: assets/fonts/Satoshi-VariableItalic.ttf
          style: italic

    - family: Lexend
      fonts:
        - asset: assets/fonts/Lexend-VariableFont_wght.ttf

    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-VariableFont_opsz,wght.ttf
        - asset: assets/fonts/Inter-Italic-VariableFont_opsz,wght.ttf
          style: italic